(source (git https://github.com/oxidizing/spin-sihl.git))
(config username "Josef Erben")
(config project_name Demo)
(config docker Yes)
(config email josef@oxidizing.io)
(config npm_username jerben)
(config github_username jerben)
(config project_description
 "A short, but powerful statement about your project")
(config ci_cd Github)
(config project_snake demo)
(config database PostgreSql)
(config project_slug demo)
(config create_switch false)
