version: "3.1"

services:
  {% if database == 'PostgreSql' -%}
  database:
    image: postgres:12.2
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dev
    ports:
      - 5432:5432
  {%- endif %}
  {% if database == 'MariaDb' -%}
  database:
    image: mariadb:10.1.41-bionic
    command: --max_allowed_packet=629145600
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: dev
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
  {%- endif %}
  adminer:
    image: adminer:4.7.6-standalone
    restart: always
    ports:
      - 8080:8080
